<h1>Cadastro de Categorias</h1>
<hr>
<form method="post" 
   action="Request.php?class=CategoryCtr&method=run">

<input type="hidden" id="id" name="id" 
    value="<?= $this->model->getId() ?>">

<label for="name">Nome da Categoria:</label>
<input type="text" name="name" id="name" required maxlenght="50" 
    value="<?= $this->model->getName() ?>">
<br>

<input type="submit" name="command" value="Novo">
<input type="submit" name="command" value="Salvar">
<input type="submit" name="command" value="Excluir">

</form>