<h1>Cadastro de Usuários</h1>

<form method="post" action="Request.php?class=UserCtr&method=run">
            <!-- input para o id (oculto) do objeto  -->
            <input type="hidden" name="id" id="id" 
                   value="<?= $this->model->getId() ?>">

            <label for="name">Nome:</label>
            <input type="text" name="name" id="name" required maxlength="50"
                   value="<?= $this->model->getName() ?>">
            <br>


            <label for="gender">Sexo:</label>
            <select name="gender" id="gender">
                <option value="M" <?= $this->model->getGender() == 'M' ? 'selected' : '' ?>
                        >Masculino</option>
                <option value="F" <?= $this->model->getGender() == 'F' ? 'selected' : '' ?> 
                        >Feminino</option>
            </select>
            <br>
            
            <label for="email">E-mail:</label>
            <input type="email" name="email" id="email" required maxlength="50"
                   value="<?= $this->model->getEmail() ?>">
            <br>
            <label for="city">Cidade:</label>
            <select id="city" name="city">
                <!-- preencher com as cidades do BD -->
                <?php
                if ($this->cities) {
                    foreach ($this->cities as $city) {
                        ?>
                        <option value="<?= $city->getId() ?>">
                           <?= $city->getName() ?>
                        </option>
                        <?php
                    }
                }
                ?>                
            </select>

            <label>Senha:
                <input type="password" id="password" required name="password" >                
            </label>
            <br>
            <button type="submit" name="command" value="Novo">
                Novo
            </button>

            <button type="submit" name="command" value="Salvar">
                Salvar
            </button>

            <button type="submit" name="command" value="Salvar">
                Excluir
            </button>

            </form>